graph LR
    A(SDT) --查找-->B([DCT])
    B --"设备状态(status)"--- C{busy?}
    D(挂到PCB任务队列)
    E[计算本次分配安全性]
    C -->|yes|D 
    C -->|no|E
    F(执行分配)
    G{save?}
    E-->G
    G-->|yes|F
    G-->|No|D

    %%C ==> D{休息时间到了}
    %%D -.yes.-> E((休息))
    %%D -.no.-> C
    %%可以用%%来注释掉某一行/添加提示
    %%E --> F(吃饭)


